# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterTakings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('cash_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('card_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_takings', models.DecimalField(decimal_places=2, max_digits=12)),
                ('register', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashup.Register')),
            ],
        ),
    ]
