# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 18:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0002_registertakings'),
    ]

    operations = [
        migrations.AddField(
            model_name='registertakings',
            name='register_open_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 14, 18, 19, 52, 30679, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registertakings',
            name='register',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cashup.Register'),
        ),
    ]
