# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 20:11
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0003_auto_20161214_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterCashup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_GBP50', models.PositiveIntegerField(default=0)),
                ('note_GBP20', models.PositiveIntegerField(default=0)),
                ('note_GBP10', models.PositiveIntegerField(default=0)),
                ('note_GBP5', models.PositiveIntegerField(default=0)),
                ('coin_GBP2', models.PositiveIntegerField(default=0)),
                ('coin_GBP1', models.PositiveIntegerField(default=0)),
                ('coin_50p', models.PositiveIntegerField(default=0)),
                ('coin_20p', models.PositiveIntegerField(default=0)),
                ('coin_10p', models.PositiveIntegerField(default=0)),
                ('coin_5p', models.PositiveIntegerField(default=0)),
                ('coin_2p', models.PositiveIntegerField(default=0)),
                ('coin_1p', models.PositiveIntegerField(default=0)),
                ('till_float', models.DecimalField(decimal_places=2, default=Decimal('225.00'), max_digits=12)),
                ('till_total', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('till_difference', models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True)),
                ('register_takings', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashup.RegisterTakings')),
            ],
        ),
    ]
