# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0004_registercashup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercashup',
            name='coin_10p',
            field=models.PositiveIntegerField(default=0, verbose_name='10p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_1p',
            field=models.PositiveIntegerField(default=0, verbose_name='1p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_20p',
            field=models.PositiveIntegerField(default=0, verbose_name='20p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_2p',
            field=models.PositiveIntegerField(default=0, verbose_name='2p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_50p',
            field=models.PositiveIntegerField(default=0, verbose_name='50p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_5p',
            field=models.PositiveIntegerField(default=0, verbose_name='5p coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_GBP1',
            field=models.PositiveIntegerField(default=0, verbose_name='£1 coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='coin_GBP2',
            field=models.PositiveIntegerField(default=0, verbose_name='£2 coins'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='note_GBP10',
            field=models.PositiveIntegerField(default=0, verbose_name='£10 notes'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='note_GBP20',
            field=models.PositiveIntegerField(default=0, verbose_name='£20 notes'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='note_GBP5',
            field=models.PositiveIntegerField(default=0, verbose_name='£5 notes'),
        ),
        migrations.AlterField(
            model_name='registercashup',
            name='note_GBP50',
            field=models.PositiveIntegerField(default=0, verbose_name='£50 notes'),
        ),
    ]
