# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0005_auto_20161215_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='outlet',
            name='name',
            field=models.CharField(default='Main Outlet', max_length=256),
            preserve_default=False,
        ),
    ]
