# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashup', '0006_outlet_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registercashup',
            name='register_takings',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cashup.RegisterTakings'),
        ),
        migrations.AlterField(
            model_name='registertakings',
            name='register',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='cashup.Register'),
        ),
    ]
